name: "Trivy Security Scan"

on:
  pull_request:
    branches: [ "main" ]
  workflow_call:

jobs:
  trivy-security-scan:
    name: Trivy vulnerability scanner
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v6.0.2

      - name: Build Docker image
        run: docker build -t check-links ./check-links

      - name: Run Trivy scan
        uses: aquasecurity/trivy-action@ed142fd0673e97e23eac54620cfb913e5ce36c25 # v0.36.0
        with:
          image-ref: 'check-links'
          format: 'table'
          severity: 'CRITICAL,HIGH'
          ignore-unfixed: true
          exit-code: '1'
