name: Merge to main

on:
  push:
    branches: ['main']

jobs:
  check-links-ci:
    uses: ./.github/workflows/check-links-ci.yml
    permissions:
      contents: read

  check-links-trivy-scan:
    uses: ./.github/workflows/check-links-trivy-scan.yml

  build-check-links-image:
    uses: ./.github/workflows/build-check-links-image.yml
    with:
      buildType: build_push
      gitRef: ${{ github.sha }}
    needs: [check-links-ci, check-links-trivy-scan]

    permissions:
      contents: read
      packages: write
      id-token: write
